#ifndef COMM_SERVER_CLIENT_CONFIG_H
#define COMM_SERVER_CLIENT_CONFIG_H

#include"commFieldsConfig.h"


#define SIZE_NUM_MSG 16

#define SIZE_AUTH_MESSAGE (SIZE_USERNAME + SIZE_PASSWORD )

#define SIZE_MSG_MESSAGE (SIZE_OBJECT + SIZE_TEXT)

#define SIZE_PERSONAL_COMPLETE_MESSAGE ( SIZE_OBJECT + SIZE_TEXT + SIZE_ID_MESSAGE)
#define SIZE_GENERIC_COMPLETE_MESSAGE ( SIZE_USERNAME + SIZE_OBJECT + SIZE_TEXT + SIZE_ID_MESSAGE)



#define COMMAND_AUTH   0x01
#define COMMAND_LOG    0x02
#define COMMAND_SUB    0x03

//sostituire il fail in alcuni casa con resend data 
//i tenativi di quanti farli e meglio averli nel server
#define COMMAND_ERR_USER_NOT_FOUND    0x04
#define COMMAND_ERR_NOT_MATCH_CREDENTIALS     0x05
#define COMMAND_ERR_USER_ALREADY_EXISTS 0x06
#define COMMAND_SUCCESS    0x07
#define COMMAND_FAILURE 0x08
#define COMMAND_CLOSE 0x09


#define COMMAND_POST_MSG 0x0A
#define COMMAND_VIEW_MSG 0x0B
#define COMMAND_VIEW_ALL_MSG 0x0C
#define COMMAND_DELETE_MSG 0x0D
#define COMMAND_QUIT 0x0E

#define COMMAND_FINISH_ATTEMPTS 0x0F


#endif
